### ISSUE TITLE
email を sendgrid に置き換えたい　

### ISSUE THREAD

**Issue by volpe28v** [volpe28v/happy_bottle#35]
gmail ではブロックされてしまうため
http://shoma2da.hatenablog.com/entry/2014/03/02/113908

**Comment by tricknotes** [comment]
あー！もしかしてぼくが Heroku の owner になっていると自由にアドオンが追加できなかったりしますかね…？
Transfer Ownership してみますー

**Comment by tricknotes** [comment]
done.
招待メールが送らさっているかと思うので、承認お願いしますー

**Comment by volpe28v** [comment]
まだアドオン追加はトライしてませんでしたが、招待メール承認させていただきました！
ありがとうございます！
